### ISSUE TITLE
Question: is it possible to use the internal clock instead of the external clock MCLK?

### ISSUE THREAD

**Issue by bbinet** [fhnw-ise-qcrypt/mcp3564#3]

**Comment by mnemocron** [comment]
Of course. You can write your own user config and select `MCP3561_CONFIG0_CLK_SEL_INT` instead of  `MCP3561_CONFIG0_CLK_SEL_EXT`

Like here:

https://github.com/fhnw-ise-qcrypt/mcp3564/blob/main/mcp3564_conf.h#L69

But external clocks are usually recommended because they have lower jitter (better effectife resolution) and better temperature stability.

**Comment by bbinet** [comment]
Ok, thank you
